/**
 * AUTO-GENERATED by docs/scripts/generate-examples.ts.
 * Do not edit by hand — re-run `pnpm generate:examples` instead.
 */

export const examples = {
    'accented/foreground': () => import('./accented/foreground'),
    'accented/primary': () => import('./accented/primary'),
    'accented/secondary': () => import('./accented/secondary'),
    'accented/standard': () => import('./accented/standard'),
    'button/disabled': () => import('./button/disabled'),
    'button/icon': () => import('./button/icon'),
    'button/outline': () => import('./button/outline'),
    'button/outline-with-color': () => import('./button/outline-with-color'),
    'button/standard': () => import('./button/standard'),
    'button/with-color': () => import('./button/with-color'),
    'card/borderless': () => import('./card/borderless'),
    'card/borderless-no-padding': () => import('./card/borderless-no-padding'),
    'card/no-padding': () => import('./card/no-padding'),
    'card/solid': () => import('./card/solid'),
    'card/solid-with-color': () => import('./card/solid-with-color'),
    'card/standard': () => import('./card/standard'),
    'card/with-color': () => import('./card/with-color'),
    'details/standard': () => import('./details/standard'),
    'header/standard': () => import('./header/standard'),
    'header/with-menu': () => import('./header/with-menu'),
    'heading/h1': () => import('./heading/h1'),
    'heading/h2': () => import('./heading/h2'),
    'heading/h3': () => import('./heading/h3'),
    'heading/h4': () => import('./heading/h4'),
    'heading/levels': () => import('./heading/levels'),
    'input/label': () => import('./input/label'),
    'input/label-placeholder': () => import('./input/label-placeholder'),
    'input/placeholder': () => import('./input/placeholder'),
    'input/solid': () => import('./input/solid'),
    'input/solid-with-color': () => import('./input/solid-with-color'),
    'input/standard': () => import('./input/standard'),
    'input/textarea': () => import('./input/textarea'),
    'input/with-color': () => import('./input/with-color'),
    'label/standard': () => import('./label/standard'),
    'label/with-color': () => import('./label/with-color'),
    'view/standard': () => import('./view/standard'),
} as const;

export type ExampleName = keyof typeof examples;
