/**
 * Walks docs/src/examples/**\/*.tsx and emits registry.generated.ts —
 * a typed map from "<component>/<variant>" to a dynamic import.
 *
 * Run as a prebuild step and on `pnpm dev` start.
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';

const EXAMPLES_DIR = path.resolve(import.meta.dirname, '..', 'src', 'examples');
const REGISTRY_PATH = path.join(EXAMPLES_DIR, 'registry.generated.ts');

async function* walk(dir: string): AsyncGenerator<string> {
    for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) yield* walk(full);
        else if (entry.isFile() && entry.name.endsWith('.tsx')) yield full;
    }
}

async function main() {
    const entries: { key: string; importPath: string }[] = [];
    for await (const file of walk(EXAMPLES_DIR)) {
        if (file === REGISTRY_PATH) continue;
        const rel = path.relative(EXAMPLES_DIR, file).replace(/\\/g, '/');
        const key = rel.replace(/\.tsx$/, '');
        const importPath = `./${key}`;
        entries.push({ key, importPath });
    }
    entries.sort((a, b) => a.key.localeCompare(b.key));

    const lines = [
        '/**',
        ' * AUTO-GENERATED by docs/scripts/generate-examples.ts.',
        ' * Do not edit by hand — re-run `pnpm generate:examples` instead.',
        ' */',
        '',
        'export const examples = {',
    ];
    for (const { key, importPath } of entries) {
        lines.push(`    '${key}': () => import('${importPath}'),`);
    }
    lines.push('} as const;', '', 'export type ExampleName = keyof typeof examples;', '');

    await fs.writeFile(REGISTRY_PATH, lines.join('\n'), 'utf8');
    console.log(`Wrote ${entries.length} example entries to ${path.relative(process.cwd(), REGISTRY_PATH)}`);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
