name: "Install"
description: "Install dependencies"

runs:
    using: "composite"
    steps:
        - name: 🏎️ Setup Node.js
          uses: actions/setup-node@v3
          with:
              node-version-file: ".nvmrc"
              registry-url: "https://registry.npmjs.org"
              cache: "npm"

        - name: 📦 Install dependencies
          shell: bash
          run: npm ci
