name: 📦 Install
description: Install dependencies

runs:
    using: 'composite'
    steps:
        - name: 🥸 Configure Git User
          shell: bash
          run: |
              git config --global user.email "opensource@nordcom.io"
              git config --global user.name "nordcombot"

        - name: 💾 Cache
          uses: actions/cache@v4
          with:
              path: |
                  ~/.bun/install/cache
                  ${{ github.workspace }}/**/.next
                  ${{ github.workspace }}/**/dist
                  ${{ github.workspace }}/**/node_modules
              key: ${{ runner.os }}-bun-build-${{ hashFiles('**/bun.lockb') }}-
              restore-keys: |
                  ${{ runner.os }}-bun-build-${{ hashFiles('**/bun.lockb') }}-
                  ${{ runner.os }}-bun-build-
                  ${{ runner.os }}-

        - name: 🏎️ Setup Bun
          uses: oven-sh/setup-bun@v1
          with:
              bun-version: canary
              no-cache: true

        - name: 📦 Install dependencies
          shell: bash
          run: bun install
