name: 'Install'
description: 'Install dependencies'

runs:
    using: 'composite'
    steps:
        - name: 🏎️ Setup Bun
          uses: oven-sh/setup-bun@v1
          with:
              bun-version: canary

        - name: 📦 Install dependencies
          shell: bash
          run: bun install --frozen-lockfile

        - name: 💾 Cache node modules
          uses: actions/cache@v4
          with:
              path: |
                  ~/.npm
                  ${{ github.workspace }}/.turbo
                  ${{ github.workspace }}/**/.next
                  ${{ github.workspace }}/**/.turbo
                  ${{ github.workspace }}/**/.vercel
              key: ${{ runner.os }}-node-build-${{ hashFiles('**bun.lockb') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
              restore-keys: |
                  ${{ runner.os }}-node-build-${{ hashFiles('**/bun.lockb') }}-
