name: Release

on:
    push:
        branches:
            - master

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}

env:
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.MACHINE_USER }}

jobs:
    release:
        name: 🚚 Release
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: 🕶️ Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: 📦 Install
              uses: ./.github/common/install

            - name: 🔨 Build
              run: bun run build:packages --no-cache

            - name: 🧪 Tests
              run: bun run test:packages

            - name: 🥸 Configure Identity
              run: |
                  git config --global user.email "opensource@nordcom.io"
                  git config --global user.name "nordcombot"

            - name: 🤝 Create Release Pull Request or Publish to NPM
              id: changesets
              uses: changesets/action@v1
              with:
                  createGithubReleases: true
                  version: bun run version
                  publish: bun run release
                  setupGitUser: false
                  commit: |
                      Changeset: Increment package & dependecy versions.

                      Congratulations on the new release! 🎉
                      This is an automated commit triggered by the `release` workflow.
                  title: 🚀 Release packages

            - name: 🫨 Create Unstable Release
              if: steps.changesets.outputs.published != 'true'
              run: |
                  git checkout master
                  bun run version:unstable
                  bun install
                  bun run release:unstable
